# Build stage
FROM public.ecr.aws/b8k8t3h1/bmgo:base as builder

WORKDIR /bmgo

COPY . .

ENV CGO_ENABLED=0

RUN make wsmkstats-build

# Runtime stage 
FROM alpine:latest

WORKDIR /

# Copy the built binary from the builder stage
COPY --from=builder  /bmgo/bin/bmgo-wsmkstats-linux-x86 /

# Optionally, if your application needs any runtime dependencies, install them here
ENV GRPC localhost:50051

# Command to run your app
CMD ./bmgo-wsmkstats-linux-x86 -logtostderr=true -v=2 -grpc-server=$GRPC
